//! Tab Title Hook
//!
//! Writes the Claude Code session id into the terminal tab title so each
//! Windows Terminal / VT-capable terminal tab is labelled with the session
//! it's running (`claude <full-uuid>`).
//!
//! ## Why a hook (and not the handler)
//!
//! The `claude-code-handler` launcher owns the spawn site and already writes
//! to `CONOUT$`, but at spawn time it only knows the session UUID for a
//! `--resume`; a *fresh* session's UUID is generated by Claude Code itself
//! *after* start. Claude Code then exports `CLAUDE_CODE_SESSION_ID` into the
//! session env, and `SessionStart` is the first lifecycle point where that id
//! is known for BOTH fresh and resumed sessions. So the hook — not the
//! handler — is the correct chokepoint.
//!
//! ## Why write to `CONOUT$` directly (not stdout)
//!
//! Hook stdout is captured by Claude Code for context injection; it never
//! reaches the terminal. To actually move the tab title we must emit the OSC
//! sequence to the console device. On Windows that's the special-name device
//! `CONOUT$` (the attached console's active screen buffer), which is immune
//! to any stdout pipe-redirection in the launcher chain. We therefore write
//! the bytes there and return a no-op `HookOutput` so nothing is injected
//! into the model's context.
//!
//! ## The sequence
//!
//! `ESC ] 0 ; <text> BEL` — OSC 0 sets BOTH the icon name and the window/tab
//! title (the most broadly-honored of the title OSCs). Windows Terminal reads
//! it and updates the tab unless the profile sets `suppressApplicationTitle`.
//!
//! ## Durability
//!
//! A single write can be clobbered later (the PowerShell prompt, or a launched
//! program, may set its own title). The dispatcher wires this hook on
//! `SessionStart` AND `UserPromptSubmit`, so the title is re-asserted on every
//! turn and keeps snapping back to the session id.

use sentinel_domain::events::{HookInput, HookOutput};

/// Environment variable Claude Code exports with the active session UUID.
const SESSION_ID_ENV: &str = "CLAUDE_CODE_SESSION_ID";

/// Opt-out: set this env var (to anything non-empty and not "0") to disable
/// the tab-title write entirely.
const OPT_OUT_ENV: &str = "SENTINEL_NO_TAB_TITLE";

/// Resolve the session id to display.
///
/// Prefers the hook payload's `session_id` (what Claude Code passed for THIS
/// event), falling back to the `CLAUDE_CODE_SESSION_ID` env var. Rejects the
/// obvious non-ids ("unknown"/empty) so we never paint a garbage title.
fn resolve_session_id(input: &HookInput, env_lookup: impl Fn(&str) -> Option<String>) -> Option<String> {
    let from_input = input
        .session_id
        .as_deref()
        .map(str::trim)
        .filter(|s| is_concrete_id(s))
        .map(str::to_string);
    if from_input.is_some() {
        return from_input;
    }
    env_lookup(SESSION_ID_ENV)
        .map(|s| s.trim().to_string())
        .filter(|s| is_concrete_id(s))
}

/// A usable session id is non-empty and not one of Claude Code's placeholder
/// sentinels.
fn is_concrete_id(s: &str) -> bool {
    !s.is_empty() && !s.eq_ignore_ascii_case("unknown") && !s.eq_ignore_ascii_case("none")
}

/// Whether the opt-out env var is set to an "on" value.
fn opted_out(env_lookup: impl Fn(&str) -> Option<String>) -> bool {
    env_lookup(OPT_OUT_ENV)
        .map(|v| {
            let v = v.trim();
            !v.is_empty() && v != "0"
        })
        .unwrap_or(false)
}

/// Build the OSC 0 "set title" byte sequence for a given title text.
///
/// `ESC ] 0 ; <text> BEL`. Any control bytes in `text` are stripped so a
/// crafted session id can't smuggle an early terminator or extra escape.
fn osc_title(text: &str) -> Vec<u8> {
    let sanitized: String = text.chars().filter(|c| !c.is_control()).collect();
    let mut seq = Vec::with_capacity(sanitized.len() + 4);
    seq.push(0x1B); // ESC
    seq.push(b']');
    seq.push(b'0');
    seq.push(b';');
    seq.extend_from_slice(sanitized.as_bytes());
    seq.push(0x07); // BEL
    seq
}

/// Write raw bytes so the OSC title sequence reaches the terminal.
///
/// Claude Code spawns hooks with their stdout redirected to a pipe (it captures
/// hook stdout for context injection), and may run them without the parent
/// tab's console attached. We therefore, in order (all safe — this crate forbids
/// `unsafe`):
///   1. `CONOUT$` — works when the hook shares the tab's console (bytes land on
///      the tab). Silently no-ops if no console is attached.
///   2. **stderr** — Claude Code redirects/captures hook *stdout*, but hook
///      *stderr* is inherited from the parent and reaches the terminal, so an
///      OSC sequence written there still moves the tab title. This is the path
///      that works in the normal harness-spawned case.
///
/// Both are attempted every call (cheap); the terminal ignores a duplicate
/// title write. Best-effort — every failure is swallowed so a title that can't
/// be set never breaks the session.
#[cfg(windows)]
fn write_to_console(bytes: &[u8]) {
    use std::io::Write as _;

    // 1. CONOUT$ (attached-console case).
    let conout_ok = match std::fs::OpenOptions::new().read(true).write(true).open("CONOUT$") {
        Ok(mut conout) => conout.write_all(bytes).and_then(|()| conout.flush()).is_ok(),
        Err(_) => false,
    };

    // 2. stderr (harness case — inherited handle reaches the tty).
    let stderr_ok = std::io::stderr()
        .write_all(bytes)
        .and_then(|()| std::io::stderr().flush())
        .is_ok();

    log_write(
        match (conout_ok, stderr_ok) {
            (true, true) => "conout+stderr",
            (true, false) => "conout",
            (false, true) => "stderr",
            (false, false) => "none",
        },
        conout_ok || stderr_ok,
    );
}

/// Diagnostic breadcrumb: append one line per invocation recording which write
/// path was taken and whether it succeeded, so the harness path is observable
/// after the fact. Best-effort; failure to log never affects the hook.
#[cfg(windows)]
fn log_write(path: &str, ok: bool) {
    use std::io::Write as _;
    if let Some(home) = dirs::home_dir() {
        let logp = home
            .join(".claude")
            .join("sentinel")
            .join("state")
            .join("tab-title.log");
        if let Some(parent) = logp.parent() {
            let _ = std::fs::create_dir_all(parent);
        }
        if let Ok(mut f) = std::fs::OpenOptions::new().create(true).append(true).open(&logp) {
            let _ = writeln!(f, "path={path} ok={ok}");
        }
    }
}

/// Non-Windows: emit to the controlling terminal via `/dev/tty` so the
/// sequence bypasses captured stdout the same way `CONOUT$` does on Windows,
/// falling back to stderr. Best-effort.
#[cfg(not(windows))]
fn write_to_console(bytes: &[u8]) {
    use std::io::Write as _;
    if let Ok(mut tty) = std::fs::OpenOptions::new().write(true).open("/dev/tty") {
        if tty.write_all(bytes).and_then(|()| tty.flush()).is_ok() {
            log_write("dev-tty", true);
            return;
        }
    }
    let ok = std::io::stderr()
        .write_all(bytes)
        .and_then(|()| std::io::stderr().flush())
        .is_ok();
    log_write("stderr-fallback", ok);
}

/// Diagnostic breadcrumb (non-Windows twin of the Windows `log_write`).
#[cfg(not(windows))]
fn log_write(path: &str, ok: bool) {
    use std::io::Write as _;
    if let Some(home) = dirs::home_dir() {
        let logp = home
            .join(".claude")
            .join("sentinel")
            .join("state")
            .join("tab-title.log");
        if let Some(parent) = logp.parent() {
            let _ = std::fs::create_dir_all(parent);
        }
        if let Ok(mut f) = std::fs::OpenOptions::new().create(true).append(true).open(&logp) {
            let _ = writeln!(f, "path={path} ok={ok}");
        }
    }
}

/// Core logic, split from `process` so it's testable without real env/console.
/// Returns the exact title string written (for assertions), or `None` when
/// nothing was written.
fn compute_title(input: &HookInput, env_lookup: impl Fn(&str) -> Option<String>) -> Option<String> {
    if opted_out(&env_lookup) {
        return None;
    }
    let session_id = resolve_session_id(input, &env_lookup)?;
    Some(format!("claude {session_id}"))
}

/// `SessionStart` / `UserPromptSubmit` entry point.
///
/// Sets the terminal tab title to `claude <session-id>` via a direct console
/// write, then returns a no-op output (no context injected, nothing shown to
/// the model). Never blocks, never fails the session.
pub fn process(input: &HookInput, _ctx: &super::HookContext<'_>) -> HookOutput {
    if let Some(title) = compute_title(input, |k| std::env::var(k).ok()) {
        write_to_console(&osc_title(&title));
    }
    HookOutput::allow()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn input_with_session(id: Option<&str>) -> HookInput {
        HookInput {
            session_id: id.map(str::to_string),
            ..Default::default()
        }
    }

    /// Build an env lookup from a fixed set of (key, value) pairs.
    fn env_from<'a>(pairs: &'a [(&'a str, &'a str)]) -> impl Fn(&str) -> Option<String> + 'a {
        move |k: &str| {
            pairs
                .iter()
                .find(|(pk, _)| *pk == k)
                .map(|(_, v)| (*v).to_string())
        }
    }

    #[test]
    fn title_from_input_session_id() {
        let input = input_with_session(Some("4554598a-be00-42a8-863e-636132d94cc4"));
        let title = compute_title(&input, env_from(&[]));
        assert_eq!(
            title.as_deref(),
            Some("claude 4554598a-be00-42a8-863e-636132d94cc4")
        );
    }

    #[test]
    fn title_falls_back_to_env_when_input_missing() {
        let input = input_with_session(None);
        let title = compute_title(
            &input,
            env_from(&[("CLAUDE_CODE_SESSION_ID", "abc-123")]),
        );
        assert_eq!(title.as_deref(), Some("claude abc-123"));
    }

    #[test]
    fn input_session_id_takes_precedence_over_env() {
        let input = input_with_session(Some("from-input"));
        let title = compute_title(
            &input,
            env_from(&[("CLAUDE_CODE_SESSION_ID", "from-env")]),
        );
        assert_eq!(title.as_deref(), Some("claude from-input"));
    }

    #[test]
    fn no_title_when_no_id_anywhere() {
        let input = input_with_session(None);
        assert_eq!(compute_title(&input, env_from(&[])), None);
    }

    #[test]
    fn placeholder_ids_are_rejected() {
        for placeholder in ["", "unknown", "UNKNOWN", "none", "None"] {
            let input = input_with_session(Some(placeholder));
            assert_eq!(
                compute_title(&input, env_from(&[])),
                None,
                "placeholder {placeholder:?} should not produce a title"
            );
        }
    }

    #[test]
    fn opt_out_suppresses_title() {
        let input = input_with_session(Some("real-id"));
        let title = compute_title(
            &input,
            env_from(&[("SENTINEL_NO_TAB_TITLE", "1")]),
        );
        assert_eq!(title, None);
    }

    #[test]
    fn opt_out_zero_is_not_opt_out() {
        let input = input_with_session(Some("real-id"));
        let title = compute_title(
            &input,
            env_from(&[("SENTINEL_NO_TAB_TITLE", "0")]),
        );
        assert_eq!(title.as_deref(), Some("claude real-id"));
    }

    #[test]
    fn osc_sequence_is_well_formed() {
        let seq = osc_title("claude xyz");
        assert_eq!(seq[0], 0x1B, "starts with ESC");
        assert_eq!(&seq[1..4], b"]0;", "OSC 0 introducer");
        assert_eq!(*seq.last().unwrap(), 0x07, "ends with BEL");
        assert_eq!(&seq[4..seq.len() - 1], b"claude xyz");
    }

    #[test]
    fn osc_strips_control_bytes_from_title() {
        // A crafted id trying to inject an early BEL + escape must be neutralized.
        let seq = osc_title("claude a\x07\x1b]0;evil");
        // No embedded ESC/BEL other than the framing ESC at [0] and BEL at end.
        assert_eq!(seq[0], 0x1B);
        assert_eq!(*seq.last().unwrap(), 0x07);
        let body = &seq[4..seq.len() - 1];
        assert!(!body.contains(&0x1B), "no embedded ESC in body");
        assert!(!body.contains(&0x07), "no embedded BEL in body");
        assert_eq!(body, b"claude a]0;evil");
    }
}
